name = "baquero-sales-report"
main = ".open-next/worker.js"
compatibility_date = "2026-05-01"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[[kv_namespaces]]
binding = "SALES_DATA"
id = "4db7634eb4d04a51be0cd295bac66349"

[vars]
DATA_PROVIDER = "kv"
